spring:
    application:
        name: nasa-apod-explorer

    datasource:
        url: jdbc:postgresql://localhost:5432/nasa_apod
        username: postgres
        password: Rahul@7965
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true

nasa:
    api:
        key: 1uceqYj3rA5O2wA6Y3N4n1bBVDOFVX0i8qyavKrR
        base-url: https://api.nasa.gov/planetary/apod

server:
    port: 8080